nama    = input("Nama                     : ")
nim     = input("NIM                      : ")
KP      = input("Kelas Paralel            : ")
TTL     = input("Tempat/Tanggal Lahir     : ")
A       = input("Alamat                   : ")
H       = input("Hobi                     : ")
NHP     = input("No. HP                   : ")

print ("\nNama                     : ", nama)
print ("NIM                      : ", nim)
print ("Kelas Paralel            : ", KP)
print ("Tempat/Tanggal Lahir     : ", TTL)
print ("Alamat                   : ", A)
print ("Hobi                     : ", H)
print ("No. HP                   : ", NHP)